const cases=[
{domain:"Housing",text:"A property firm asks whether living area predicts sale price and wants a pricing recommendation.",q:"How much does expected sale price change with living area for comparable properties?",data:"missing",model:"outlier",story:"causal"},
{domain:"Energy",text:"A facilities manager asks whether monthly electricity use differs across three building types.",q:"Do mean electricity-use levels differ across building types?",data:"unit",model:"spread",story:"people"},
{domain:"Labor",text:"A recruiter asks whether training completion is associated with six-month retention.",q:"Is training completion associated with six-month retention in this workforce?",data:"duplicate",model:"small",story:"causal"},
{domain:"Air travel",text:"A travel manager asks whether distance predicts average fare and wants a budgeting rule.",q:"How does average fare vary with distance in the observed markets?",data:"missing",model:"curve",story:"extrapolate"}
];
const options={
data:[["missing","Missing values coded as zero"],["unit","Mixed measurement units"],["duplicate","Duplicate records"],["none","No data-quality problem"]],
model:[["outlier","Influential outlier"],["spread","Unequal group spreads"],["small","Sparse expected counts"],["curve","Nonlinear pattern"],["none","No assumption concern"]],
story:[["causal","Association stated as causation"],["people","Group averages used to stereotype individuals"],["extrapolate","Recommendation extrapolates beyond observed data"],["none","No interpretation concern"]]
};
const seed=document.querySelector("#seed"),feedback=document.querySelector("#feedback");let current;
function radios(root,name,items){root.innerHTML=items.map(([v,t])=>`<label class="choice"><input type="radio" name="${name}" value="${v}"><span>${t}</span></label>`).join("")}
radios(document.querySelector("#dataOptions"),"data",options.data);radios(document.querySelector("#modelOptions"),"model",options.model);radios(document.querySelector("#storyOptions"),"story",options.story);
function load(){const s=Math.max(1,Math.floor(Number(seed.value)||2150));seed.value=s;current=cases[(s*13+s%5)%cases.length];document.querySelector("#case").textContent=current.text;document.querySelector("#domain").textContent=current.domain;document.querySelector("#question").value=current.q;document.querySelector("#method").value="";document.querySelector("#limit").value="";document.querySelectorAll('input[type=radio]').forEach(x=>x.checked=false);feedback.innerHTML='<div class="result"><h3>Case loaded</h3><p>Choose a method, write one diagnostic, and identify the three challenges.</p></div>';}
document.querySelector("#load").onclick=load;document.querySelector("#next").onclick=()=>{seed.value=Number(seed.value)+1;load();};
document.querySelector("#check").onclick=()=>{const pick=n=>document.querySelector(`input[name="${n}"]:checked`)?.value,method=document.querySelector("#method").value,limit=document.querySelector("#limit").value.trim(),answers=[pick("data"),pick("model"),pick("story")];if(!method||!limit||answers.some(x=>!x)){feedback.innerHTML='<div class="result warning"><h3>Investigation incomplete</h3><p>Choose a method, record a diagnostic, and answer all three challenge prompts.</p></div>';return;}const keys=[current.data,current.model,current.story],score=answers.filter((x,i)=>x===keys[i]).length;const label=(set,key)=>options[set].find(x=>x[0]===key)[1];feedback.innerHTML=`<div class="result ${score===3?"success":score===0?"error":"warning"}"><h3>${score}/3 challenges identified</h3><p><strong>Data:</strong> ${label("data",current.data)}. <strong>Model:</strong> ${label("model",current.model)}. <strong>Interpretation:</strong> ${label("story",current.story)}.</p><p>Your written limitation matters: a defensible workflow records the issue, shows how it was checked, and states how it changes the recommendation.</p><p><strong>Biblical/Ethical Stewardship and Integrity:</strong> truthfulness requires an analysis another person could audit; humility requires naming what the evidence cannot establish; neighbor-love requires considering who benefits or bears risk.</p></div>`;};
load();